filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - condition:
            or:
              - contains:
                  docker.container.image: "dreamspace04/"
              - equals:
                  docker.container.name: "eureka-server"
              - equals:
                  docker.container.name: "api-gateway"
              - equals:
                  docker.container.name: "authentication-service"
              - equals:
                  docker.container.name: "employee-service"
              - equals:
                  docker.container.name: "leave-management-service"
              - equals:
                  docker.container.name: "notification-service"
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              processors:
                - add_docker_metadata:
                    host: "unix:///var/run/docker.sock"

processors:
  - add_host_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
