version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  jaeger:
    image: jaegertracing/all-in-one:1.50
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger Web UI
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "9411:9411"   # Zipkin v2 json receiver

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: dreamspace04/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: dreamspace04/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED=true
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces

  authentication-service:
    build:
      context: .
      dockerfile: authentication-service/Dockerfile
    image: dreamspace04/authentication-service:latest
    container_name: authentication-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces

  employee-service:
    build:
      context: .
      dockerfile: employee-service/Dockerfile
    image: dreamspace04/employee-service:latest
    container_name: employee-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces

  leave-management-service:
    build:
      context: .
      dockerfile: leave-management-service/Dockerfile
    image: dreamspace04/leave-management-service:latest
    container_name: leave-management-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    image: dreamspace04/notification-service:latest
    container_name: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4318/v1/traces
